### PR TITLE
Desktop - Tablet: Reward Pools breakpoint issues #86

### PR DESCRIPTION
**Pull request by irinawork**

### CODE REVIEW

**Comment by captnocap** [comment]
@irinawork 

Cards are sized nicely. however, maybe just myself, the padding on the headers seem too much. 

There are two solutions I can think of off the top of my head here:
1) Reduce the padding globally. so that it would read like so 
image
and not like 
image
(take note of open space between two images)

2) change the layout of the header to fit the padding. 

side note: I did also notice this is breaking on 1440x900 
image
notice how the cards for 'Total Gas Rewards' Is larger than the others. this is when on 1440x900 with the side menu open. 

it should just scale down from when the side menu is closed: 
image
notice how all of these cards are the same. 
this is not an issue above 1440x900 or on mobile.

**Comment by OPPandaDeFi** [comment]
To note @captnocap the extra height on the 1440x900 is probably fine as the text is too long to fit on one line for some of those like it does on the second one. Making that font smaller might work, but also just might make it hard to read.

It might be best to just allow some rows be thicker then others and make all the boxes(not all rows just the boxes in each row) match the largest height boxes in its row to make it look cleaner. And center the content.

**Comment by OPPandaDeFi** [comment]
Though also this PR didn't specifically change how those header boxes looked.

**Comment by OPPandaDeFi** [comment]
For this specific issue. @irinawork I have an idea of what would feel right. 

Come of its already there, but setting a min-height on the header isnt exactly the right fix for getting them to be the same size. At weird sizes it can still have issues and the forced padding on normal views does look off like cap was saying. 

image

I think the best looking result would involve a mix of the following.
https://codepen.io/felinuxltda/pen/KKVVYYN
https://stackoverflow.com/a/70608516

Maybe its not worth it. Would love to hear your opinion.

**Comment by OPPandaDeFi** [comment]
Also making the button and details toggle flow to the bottom of the card would probably look nice. 
image

**Comment by captnocap** [comment]
incomplete

**Pull request closed without merging**
