### PR TITLE
Reward Hub: Row View #47

### PR DESCRIPTION
**Pull request by irinawork**

### CODE REVIEW

**Comment by captnocap** [comment]
@irinawork 

Looks good on desktop, tablet and mobile. 

### Issues
mobile has lost the ability to switch between row view and card view however. need to put that in for mobile to have the ability to switch display.

**Comment by OPPandaDeFi** [comment]
Rows look good. Just need to reenable the mobile switcher like cap mentioned. 

Probably new issue: The tooltips all have a generic "Hi im a tooltip" text on them. Should switch it to something relevant. @captnocap  And when you click on the tooltip icon its redirecting to the home page. 

Once this is merged we will need to setup all the connect/data/deposit/withdraw/harvest functions. I initial did some of them but only finished the card version with final touches once I pulled the rows out.

**Comment by captnocap** [comment]
> Rows look good. Just need to reenable the mobile switcher like cap mentioned.


@irinawork

**Comment by captnocap** [comment]
incomplete

**Pull request closed without merging**
